import Image from "next/image";
import React from "react";

export const metadata = {
  title: "Anmol Ashish - Portfolio",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <article className="about active" data-page="about">
        <header>
          <h2 className="h2 article-title">About Me</h2>
        </header>

        <section className="about-text">
          <p>
            I am a skilled Front-End Developer from Jalandhar, Punjab, with a
            strong foundation in HTML, CSS, and JavaScript. I specialize in
            building responsive and user-centric web applications and have
            proficiency in utilizing modern frameworks like React and Next.js to
            craft engaging user experiences.
          </p>

          <p>
            My passion lies in creating exceptional digital experiences by
            solving complex problems through innovative designs and efficient
            development. I aim to combine functionality with aesthetics,
            ensuring that your website is both intuitive and visually appealing.
          </p>
        </section>

        <section className="service">
          <h3 className="h3 service-title">My Expertise</h3>

          <ul className="service-list">
            <li className="service-item">
              <div className="service-icon-box">
                <Image
                  src="/images/icon-dev.svg"
                  alt="Web development icon"
                  width="40"
                  height={40}
                />
              </div>

              <div className="service-content-box">
                <h4 className="h4 service-item-title">
                  Website Design & Development
                </h4>

                <p className="service-item-text">
                  Expertise in crafting responsive, user-friendly websites using
                  modern tools and frameworks like React and Next.js.
                </p>
              </div>
            </li>

            <li className="service-item">
              <div className="service-icon-box">
                <Image
                  src="/images/icon-design.svg"
                  alt="Frontend design icon"
                  width="40"
                  height={40}
                />
              </div>

              <div className="service-content-box">
                <h4 className="h4 service-item-title">Frontend Development</h4>

                <p className="service-item-text">
                  Proficient in creating interactive and visually appealing
                  interfaces with a focus on user experience.
                </p>
              </div>
            </li>

            <li className="service-item">
              <div className="service-icon-box">
                <Image
                  src="/images/icon-app.svg"
                  alt="mobile app icon"
                  width="40"
                  height={40}
                />
              </div>

              <div className="service-content-box">
                <h4 className="h4 service-item-title">Backend Integration</h4>

                <p className="service-item-text">
                  Skilled in integrating backend technologies to deliver dynamic
                  and feature-rich web applications.
                </p>
              </div>
            </li>

            <li className="service-item">
              <div className="service-icon-box">
                <Image
                  src="/images/icon-photo.svg"
                  alt="camera icon"
                  width="40"
                  height={40}
                />
              </div>

              <div className="service-content-box">
                <h4 className="h4 service-item-title">
                  Data Analysis & Visualization
                </h4>

                <p className="service-item-text">
                  Experienced in analyzing data and presenting actionable
                  insights through visually engaging dashboards and reports.
                </p>
              </div>
            </li>
          </ul>
        </section>
      </article>
    </div>
  );
}
