import Image from "next/image";
import React from "react";

export const metadata = {
  title: "Anmol ashish - Certificates",
  description: "Generated by create next app",
};

export default function page() {
  const certificates = [
    {
      id: 1,
      name: "Internship and Job Preparation",
      image: "/images/certificate-1.jpeg",
      "image-alt": "Certification for Internship and Job Preparation",
      date: "Mar 29, 2023",
      description: `The training consisted of Getting Started with the Job Hunt,
                    Building up your Gears, Going at the Front, and The Final
                    Project modules.`,
      link: "",
    },
    {
      id: 2,
      name: "Programming with Python",
      image: "/images/certificate-2.jpeg",
      "image-alt": "Certificate for Programming with Python",
      date: "Feb 12, 2024",
      description: `The training consisted of Basics of Programming in Python,
                    Principles of Object-Oriented Programming (OOP), Connecting
                    to SQLite Database, Developing a GUI with PyQT, Application
                    of Python in Various Disciplines.`,
      link: "",
    },
    {
      id: 3,
      name: "Core Java",
      image: "/images/certificate-3.jpeg",
      "image-alt": "Certificate for Core Java",
      date: "Apr 16, 2023",
      description: `This training consisted of Getting Started with Java,
                    Leveraging Basic Concepts, Object-Oriented Programming, and
                    Java Development Modules.`,
      link: "",
    },
    {
      id: 4,
      name: "Web Development",
      image: "/images/certificate-4.jpeg",
      "image-alt": "Certificate for Web Development",
      date: "Feb 10, 2024",
      description: `This training consisted of HTML, CSS, Bootstrap, DBMS, PHP,
                    React, and Final Projects.`,
      link: "",
    },
    {
      id: 5,
      name: "Programming with C and C++",
      image: "/images/certificate-5.jpeg",
      "image-alt": "Certificate for C and C++",
      date: "Mar 25, 2023",
      description: `The training consisted of Diving into C Programming,
                    Fundamentals of Object-Oriented Programming Using C++,
                    Diving into C++ Programming, and Building Cricket Game
                    Application Modules.`,
      link: "",
    },
    {
      id: 6,
      name: "Responsive Web Design",
      image: "/images/certificate-6.jpeg",
      "image-alt": "Certificate for Responsive Web Design",
      date: "Jan 26, 2024",
      description: `This training teaches HTML, CSS, and modern techniques for
                    building responsive websites through projects like cat photo
                    apps, penguin layouts, and photo galleries.`,
      link: "",
    },
    {
      id: 7,
      name: "JavaScript Algorithm and Data Structure",
      image: "/images/certificate-7.jpeg",
      "image-alt": "Certificate for JavaScript Algorithm and Data Structure",
      date: "Feb 14, 2024",
      description: `I honed my JavaScript skills in variables, arrays, objects,
                    and more through the JavaScript Algorithm and Data
                    Structures Certification, diving deeper into OOP, functional
                    programming, algorithms, local storage, and API fetching.`,
      link: "",
    },
  ];

  return (
    <div>
      <article className="blog active" data-page="certificates">
        <header>
          <h2 className="h2 article-title">Certificates</h2>
        </header>

        <section className="blog-posts">
          <ul className="blog-posts-list">
            {certificates.map((element) => {
              return (
                <li className="blog-post-item" key={element.id}>
                  <a href="#">
                    <figure className="blog-banner-box">
                      <Image
                        src={element.image}
                        alt={element["image-alt"]}
                        width={800}
                        height={800}
                      />
                    </figure>

                    <div className="blog-content">
                      <div className="blog-meta">
                        <p className="blog-category">Date</p>

                        <span className="dot"></span>

                        <time dateTime="2023-03-29">{element.date}</time>
                      </div>

                      <h3 className="h3 blog-item-title">{element.name}</h3>

                      <p className="blog-text">{element.description}</p>
                    </div>
                  </a>
                </li>
              );
            })}
          </ul>
        </section>
      </article>
    </div>
  );
}
