import React from "react";
import { IoBookOutline } from "react-icons/io5";

export const metadata = {
  title: "Anmol ashish - Resume",
  description: "Generated by create next app",
};

export default function page() {
  const education = [
    {
      id: 1,
      title: "Bachelor of Technology (B.Tech) in Computer Science",
      "time-span": "2021 — 2025",
      description: `Pursuing a degree in Computer Science at Lyallpur Khalsa College Technical Campus, Jalandhar, Punjab, focusing on modern web technologies and development practices.`,
    },
    {
      id: 2,
      title: "High School",
      "time-span": "2019 — 2021",
      description: `Graduated from Junior Model School, Jalandhar, Punjab, with a strong foundation in computer science and mathematics.`,
    },
  ];

  const timelineData = [
    {
      id: 5,
      title: "Skillvarz Hackathon",
      year: "2025",
      description:
        "Built innovative solutions during a competitive hackathon, leveraging design and development skills to achieve functional outcomes.",
    },
    {
      id: 4,
      title: "React/Next.js Developer",
      year: "2025 - Present",
      description:
        "Contributed to 4+ projects, building and optimizing web applications with modern front-end technologies.",
    },
    {
      id: 1,
      title: "Varun Anand Portfolio (Live Project)",
      year: "2024",
      description:
        "Led the development of a poet website for Shayar Varun Anand using Next.js, React, and MongoDB, ensuring dynamic content rendering, responsive design, and optimized performance.",
    },
    {
      id: 3,
      title: "Reimagination Hackathon",
      year: "2024",
      description:
        "Built innovative solutions during a competitive hackathon, leveraging design and development skills to achieve functional outcomes.",
    },
    {
      id: 2,
      title: "Trainee at Elleen Infotech",
      year: "2023",
      description:
        "Acquired essential web development skills by actively contributing to team projects and completing 5+ modules in HTML, CSS, and JavaScript during a one-month training program.",
    },
  ];

  const skillsData = [
    {
      id: 1,
      name: "HTML",
      percentage: 95,
    },
    {
      id: 5,
      name: "CSS",
      percentage: 95,
    },
    {
      id: 2,
      name: "JavaScript",
      percentage: 90,
    },
    {
      id: 3,
      name: "React JS",
      percentage: 85,
    },
    {
      id: 6,
      name: "Next JS",
      percentage: 75,
    },
    {
      id: 4,
      name: "REST APIs",
      percentage: 65,
    },
    {
      id: 7,
      name: "Bootstrap",
      percentage: 85,
    },
    {
      id: 8,
      name: "Tailwind",
      percentage: 95,
    },
    {
      id: 9,
      name: "Flask",
      percentage: 55,
    },
    {
      id: 10,
      name: "Git",
      percentage: 95,
    },
  ];

  return (
    <div>
      <article className="resume active" data-page="resume">
        <header>
          <h2 className="h2 article-title">Resume</h2>
        </header>

        <section className="timeline">
          <div className="title-wrapper">
            <div className="icon-box">
              <IoBookOutline />
            </div>

            <h3 className="h3">Education</h3>
          </div>

          <ol className="timeline-list">
            {education.map((element) => {
              return (
                <li className="timeline-item" key={element.id}>
                  <h4 className="h4 timeline-item-title">{element.title}</h4>

                  <span>{element["time-span"]}</span>

                  <p className="timeline-text">{element.description}</p>
                </li>
              );
            })}
          </ol>
        </section>

        <section className="timeline">
          <div className="title-wrapper">
            <div className="icon-box">
              <IoBookOutline />
            </div>

            <h3 className="h3">Experiences</h3>
          </div>

          <ol className="timeline-list">
            {timelineData.map((element) => {
              return (
                <li className="timeline-item" key={element.id}>
                  <h4 className="h4 timeline-item-title">{element.title}</h4>

                  <span>{element.year}</span>

                  <p className="timeline-text">{element.description}</p>
                </li>
              );
            })}
          </ol>
        </section>

        <section className="skill">
          <h3 className="h3 skills-title">My Skills</h3>

          <ul className="skills-list content-card">
            {skillsData.map((skill) => (
              <li className="skills-item" key={skill.id}>
                <div className="title-wrapper">
                  <h5 className="h5">{skill.name}</h5>
                  <data value={skill.percentage}>{skill.percentage}%</data>
                </div>

                <div className="skill-progress-bg">
                  <div
                    className="skill-progress-fill"
                    style={{ width: `${skill.percentage}%` }}
                  ></div>
                </div>
              </li>
            ))}
          </ul>
        </section>
      </article>
    </div>
  );
}
