import React from "react";
import { IoBookOutline } from "react-icons/io5";

export const metadata = {
  title: "Anmol ashish - Resume",
  description: "Generated by create next app",
};

export default function page() {
  const education = [
    {
      id: 1,
      title: "Bachelor of Technology (B.Tech) in Computer Science",
      "time-span": "2021 — 2025",
      description: `Pursuing a degree in Computer Science at Lyallpur Khalsa College Technical Campus, Jalandhar, Punjab, focusing on modern web technologies and development practices.`,
    },
    {
      id: 2,
      title: "High School",
      "time-span": "2019 — 2021",
      description: `Graduated from Junior Model School, Jalandhar, Punjab, with a strong foundation in computer science and mathematics.`,
    },
  ];

  const timelineData = [
    {
      id: 1,
      title: "Live Project",
      year: "2024",
      description:
        "Led the development of a poet website for Shayar Varun Anand using Next.js, React, and Node.js, ensuring dynamic content rendering, responsive design, and optimized performance.",
    },
    {
      id: 2,
      title: "Trainee at Elleen Infotech",
      year: "2023",
      description:
        "Acquired essential web development skills by actively contributing to team projects and completing 5+ modules in HTML, CSS, and JavaScript during a one-month training program.",
    },
    {
      id: 3,
      title: "Reimagination Hackathon",
      year: "2024",
      description:
        "Built innovative solutions during a competitive hackathon, leveraging design and development skills to achieve functional outcomes.",
    },
  ];

  return (
    <div>
      <article className="resume active" data-page="resume">
        <header>
          <h2 className="h2 article-title">Resume</h2>
        </header>

        <section className="timeline">
          <div className="title-wrapper">
            <div className="icon-box">
              <IoBookOutline />
            </div>

            <h3 className="h3">Education</h3>
          </div>

          <ol className="timeline-list">
            {education.map((element) => {
              return (
                <li className="timeline-item" key={element.id}>
                  <h4 className="h4 timeline-item-title">{element.title}</h4>

                  <span>{element["time-span"]}</span>

                  <p className="timeline-text">{element.description}</p>
                </li>
              );
            })}
          </ol>
        </section>

        <section className="timeline">
          <div className="title-wrapper">
            <div className="icon-box">
              <IoBookOutline />
            </div>

            <h3 className="h3">Achievements</h3>
          </div>

          <ol className="timeline-list">
            {timelineData.map((element) => {
              return (
                <li className="timeline-item" key={element.id}>
                  <h4 className="h4 timeline-item-title">{element.title}</h4>

                  <span>{element.year}</span>

                  <p className="timeline-text">{element.description}</p>
                </li>
              );
            })}
          </ol>
        </section>

        <section className="skill">
          <h3 className="h3 skills-title">My Skills</h3>

          <ul className="skills-list content-card">
            <li className="skills-item">
              <div className="title-wrapper">
                <h5 className="h5">HTML/CSS</h5>
                <data value="95">95%</data>
              </div>

              <div className="skill-progress-bg">
                <div
                  className="skill-progress-fill"
                  style={{ width: "95%" }}
                ></div>
              </div>
            </li>

            <li className="skills-item">
              <div className="title-wrapper">
                <h5 className="h5">JavaScript</h5>
                <data value="90">90%</data>
              </div>

              <div className="skill-progress-bg">
                <div
                  className="skill-progress-fill"
                  style={{ width: "90%" }}
                ></div>
              </div>
            </li>

            <li className="skills-item">
              <div className="title-wrapper">
                <h5 className="h5">React & Next.js</h5>
                <data value="85">85%</data>
              </div>

              <div className="skill-progress-bg">
                <div
                  className="skill-progress-fill"
                  style={{ width: "85%" }}
                ></div>
              </div>
            </li>

            <li className="skills-item">
              <div className="title-wrapper">
                <h5 className="h5">REST APIs</h5>
                <data value="75">75%</data>
              </div>

              <div className="skill-progress-bg">
                <div
                  className="skill-progress-fill"
                  style={{ width: "75%" }}
                ></div>
              </div>
            </li>
          </ul>
        </section>
      </article>
    </div>
  );
}
